swiftmailer:
    #    url: '%env(MAILER_URL)%'
    transport: smtp
    encryption: tls
    port: 587
    host: localhost
    username: administrator
    password: Pa$$w0rd
    spool: { type: 'memory' }
