swiftmailer:
    #    url: '%env(MAILER_URL)%'
    transport: smtp
    encryption: tls
    port: 587
    host: smtp-mail.outlook.com
    username: ameline.aubin2018@campus-eni.fr
    password:
    spool: { type: 'memory' }
