<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{


    /**
     * @Route(
     *     "/logout",
     *     name="app_logout")
     */
    public function logout(){}


    /**
     * @Route(
     *     "/",
     *     name="app_login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route(
     *     "/mon-profil",
     *     name="app_my_profile",
     *     methods={"GET", "POST"}
     *     )
     * @param UserPasswordEncoderInterface $encoder
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function updateMyProfile(UserPasswordEncoderInterface $encoder, Request $request )
    {
        $currentUser = $this->getUser();

        $registerForm = $this->createForm(UserType::class, $currentUser);
        $registerForm->handleRequest($request);

        if($registerForm->isSubmitted() && $registerForm->isValid()){

            $password = $currentUser->getPassword();
            $hash = $encoder->encodePassword($currentUser, $password);
            $currentUser->setPassword($hash);

            //Si le user veut uploader
            if(null!==$registerForm->get("profilePictureName")->getData()){
                //Permet d'ajouter une photo
                //TODO gérer la suppression des photos préexistantes. cf fichier pour uploader une photo, dans un des liens.
                //récupération du fichier photo
                $profilePicture = $registerForm->get("profilePictureName")->getData();
                //construction du nom de fichier unique avec l'extension réelle du fichier
                $profilePictureName=$this->generateUniqueFileName().'.'.$profilePicture->guessExtension();
                //déplacement du fichier dans le répertoire à photo de profil
                try{
                    $profilePicture->move(
                        $this->getParameter('profile_pictures_directory'),
                        $profilePictureName
                    );
                }catch (FileException $e){

                }
                // attribution du nom de fichier dans l'objet User
                $currentUser->setProfilePictureName($profilePictureName);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($currentUser);
            $em->flush();

            $this->addFlash("success", 'Votre compte a bien été modifié ! ');
            return $this->redirectToRoute('home');
        }


        return $this->render('security/myprofile.html.twig',[
          'registerForm'=>$registerForm->createView(),
          'user'=>$currentUser
        ]);

    }

    /**
     * @Route("/profil/{id}",
     *     name="show_profile",
     *     requirements={"id"="\d+"})
     * @param $id
     * @return Response
     */
    public function showProfile($id)
    {
        $em=$this->getDoctrine()->getRepository(User::class);
        $user = $em->find($id);
        return $this->render('app/show-profile.html.twig', [
           'user'=>$user
        ]);
    }


    //sert dans register() pour l'upload de photo
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     * allow a user registration manually by an admin
     * @IsGranted("ROLE_ADMIN")
     * @Route("/inscrire-utilisateur",
     *     name="app_register",
     *     methods={"GET", "POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function registerUser(UserPasswordEncoderInterface $encoder, Request $request, \Swift_Mailer $swift_Mailer)
    {
        $user = new User();
        $registerForm = $this->createForm(UserType::class, $user);
        $registerForm->handleRequest($request);

        if($registerForm->isSubmitted() && $registerForm->isValid()){

            $password = $user->getPassword();
            $hash = $encoder->encodePassword($user, $password);
            $user->setPassword($hash);

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            //send an email with informations to connect
            $message = new \Swift_Message();
            $message->setTo($user->getEmail())
                    ->setSubject("Votre inscription")
                    ->setFrom("ameline.aubin2018@campus-eni.fr")
                    ->setBody("mail");
            $swift_Mailer->send($message);
            return $this->redirectToRoute('home');
        }

        return $this->render('myprofile.html.twig', [
            'registerForm' => $registerForm->createView()
        ]);

    }


}
